// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFtbQUAumnCKhK24be_Odv1wbCwetCAoM',
    appId: '1:607782951885:web:de0eb87f57fdb87cbe4284',
    messagingSenderId: '607782951885',
    projectId: 'vega-b3c34',
    authDomain: 'vega-b3c34.firebaseapp.com',
    storageBucket: 'vega-b3c34.appspot.com',
    measurementId: 'G-J2YSV2Y4SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUKLeDdyW8z_Ag2opGBvbTQF4OsFJt0Wo',
    appId: '1:155032276852:android:969418b03a537e6a89e621',
    messagingSenderId: '155032276852',
    projectId: 'vega-4c634',
    storageBucket: 'vega-4c634.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB20Jv7WGBVv1HlEWALsP7ABYSe3NMuDZI',
    appId: '1:155032276852:ios:c084b1db10edd5b289e621',
    messagingSenderId: '155032276852',
    projectId: 'vega-4c634',
    storageBucket: 'vega-4c634.firebasestorage.app',
    iosBundleId: 'com.example.vega',
  );

}